name: Build and Release Aseprite

on:
  push:
    branches: [ main ]
  workflow_dispatch: # 允许手动点击运行

jobs:
  build:
    runs-on: ubuntu-latest # 使用 Ubuntu 系统

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # 升级到 v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ cmake ninja-build libx11-dev libxcursor-dev libxi-dev libgl1-mesa-dev libfontconfig1-dev

      - name: Clone Aseprite source
        run: git clone --recursive https://github.com/aseprite/aseprite.git

      - name: Build Aseprite
        run: |
          cd aseprite
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
          ninja aseprite

      - name: Upload Artifact
        uses: actions/upload-artifact@v4 # 这里必须用 v4，不然会报错！
        with:
          name: aseprite-linux-build
          path: aseprite/build/bin/aseprite
